CHROMIUM_FLAGS="--use-cmd-decoder=passthrough
--enable-features=VaapiIgnoreDriverChecks,VaapiLowPowerEncoderGen9x,Vp9kSVCHWDecoding,VaapiVp9kSVCHWEncoding,DesktopScreenshots,SharingDesktopScreenshotsEdit,WebUIDarkMode,PlatformHEVCDecoderSupport,PlatformHEVCEncoderSupport,PartialRaster,CanvasOopRasterization,AcceleratedVideoDecoder,AcceleratedVideoEncoder,AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,UseMultiPlaneFormatForHardwareVideo,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE
--ignore-gpu-blocklist 
--disable-gpu-driver-bug-workaround
--disable-features=ExtensionManifestV2Unsupported,ExtensionManifestV2Disabled --oauth2-client-id=77185425430.apps.googleusercontent.com --oauth2-client-secret=OTJgUOQcT7lO7GsGZq2G4IlT
--disk-cache-dir=/run/user/1000/chromium-cache
--disk-cache-size=419430400
--enable-chrome-browser-cloud-management
--show-component-extension-options
--enable-gpu-rasterization
--media-router=0
--enable-remote-extensions
--video-capture-use-gpu-memory-buffer 
--enable-video-player-chromecast-support
--enable-pixel-canvas-recording
--enable-native-gpu-memory-buffers
--enable-zero-copy
--enable-partial-raster
--enable-parallel-downloading
--enable-quic
--enable-lazy-image-loading
--enable-lcd-text
--enable-oop-rasterization
--canvas-oop-rasterization
--enable-gpu-compositing
--enable-accelerated-mjpeg-decode
--enable-font-antialiasing
--enable-accelerated-2d-canvas
--enable-gpu-memory-buffer-video-frames
--enable-gpu-memory-buffer-compositor-resources
--enable-hardware-overlays"